### PR TITLE
sof-hda-dsp: Add speaker led support

### PR DESCRIPTION
**Pull request by Kobatw**
There's a speaker led on Dell G16 and use sof-hda-dsp to control.

### CODE REVIEW

**Comment by Kobatw** [comment]
@perexg would you please take a review!? thanks

**Comment by chinyakao** [comment]
@perexg Could you help to review this PR?

**Comment by chinyakao** [comment]
Hello @perexg ,
The speaker mute hot key's LED indicator needs to be controlled by sof-hda-dsp for Dell G16 notebook.
Could you help to check if it is a valid change?

Thanks,

**Comment by chinyakao** [comment]
Hi @Kobatw ,

Could you revise the commit as the dynamic parameter to set the LED on/off instead of hardcoding on card1? e.g., card${CardNumber}
Too much-customized code may make the reviewer concerned to agree to this patch.

Thanks,
Riley

**Comment by Kobatw** [comment]
I have sent V2 please ignore this PR.

**Comment by perexg** [comment]
V2 is #302. Please, force push (git -f) to the same branch next time. Creating multiple requests for one issue is not a good habit.

**Comment by Kobatw** [comment]
> V2 is #302. Please, force push (git -f) to the same branch next time. Creating multiple requests for one issue is not a good habit.

ok, thanks

**Pull request closed without merging**
