### PR TITLE
Add Use Case for Arturia Minifuse 2

### PR DESCRIPTION
**Pull request by nodens**
Arturia Minifuse 2
(https://www.arturia.com/products/audio/minifuse/minifuse2)
is an USB audio interface with 2 mono inputs and 2 channel outputs.
It uses 1 subinterface with 4 capture and 4 playback channels:
Capture channels:
- Mic/Line/Inst 1 (Mono)
- Mic/Line/Inst 2 (Mono)
- Loopback (Stereo, L+R)

Playback:
- Main (Stereo, L+R)
- Loopback (L+R)

The Loopback capture and playback are intended to ease recording sound
from the computer, e.g if you're doing a podcast and want to record
something that plays from the computer. Of course us linux user don't
need that, since we have many tools able to do that.

However, without a dedicated use case, alsa treats the channels as
surround 4.0, which make the card difficult to use.

At this stage, no controls are available.

TODO/FIXMEs:
- add a channel map override on the pcm device ?

### CODE REVIEW

**Comment by nodens** [comment]
Hi !
I struggled a bit to make this one (even using GoXLR as an example), because it's a bit of a strange beast, especially as lsusb don't show the descriptions for all the channels text descriptors (https://github.com/gregkh/usbutils/issues/144).

Here is the alsa-info:
[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8405219/alsa-info.txt)
 
I'm still trying to figure out 2 things:
- how to explicitly add back the fallback "Pro Audio" profile as some people might prefer it for some situations ?
- I'm afraid the driver is still using the surround40 channel names and I'm not sure if I should add an chmap override somewhere ?

```
numid=2,iface=PCM,name='Capture Channel Map'
  ; type=INTEGER,access=r----R--,values=4,min=0,max=36,step=0
  : values=3,4,7,8
  | container
    | chmap-fixed=FL,FR,FC,LFE
numid=1,iface=PCM,name='Playback Channel Map'
  ; type=INTEGER,access=r----R--,values=4,min=0,max=36,step=0
  : values=3,4,7,8
  | container
    | chmap-fixed=FL,FR,FC,LFE
```

Thanks for reviewing/helping and all the fish!

**Comment by perexg** [comment]
> how to explicitly add back the fallback "Pro Audio" profile as some people might prefer it for some situations

Add new verb file (like HiFi, but call it Multichannel HiFi or so) without any LibraryConfig to export directly the hw: driver devices without any modification.

> `numid=1,iface=PCM,name='Playback Channel Map'`

You cannot override those controls defined by the driver. They are for the hw: devices (direct access). But you may override the channel map in the library configuration for apps:

```
	slave {
			pcm {
				type hw
				card $CARD
				device 0
                                chmaps [ FL FR ]
			}
			channels 4
		}
       }
```

**Comment by nodens** [comment]
> Add new verb file (like HiFi, but call it Multichannel HiFi or so) without any LibraryConfig to export directly the hw: driver devices without any modification.

Thanks! I did just that.

> You cannot override those controls defined by the driver. They are for the hw: devices (direct access). But you may override the channel map in the library configuration for apps:

OK. So far it didn't seem to cause any issue to apps, since 2 channels are exposed per Device. I guess it would make sense to handle this in the kernel driver, but I'm not convinced it's worth it, the use case should make things clear enough.

**Comment by nodens** [comment]
It does look cleaner!

I'm happy to try it out, but what do you mean by very latest alsa-lib?

I have 1.2.6.1 (debian unstable), which seems to be the latest available as a release upstream, but when I try to replace the UCM configs I get the following error:

```
➤  alsaucm reload
ALSA lib parser.c:2021:(parse_master_file) Incompatible syntax 6 in sof-hda-dsp.conf
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -22
alsaucm: error failed to open sound card hw:0: Invalid argument
✘  ~/src/alsa/alsa-ucm-conf [:75c2a63|✔ ]
➤  alsaucm reload -c hw:1
ALSA lib parser.c:2021:(parse_master_file) Incompatible syntax 6 in USB-Audio.conf
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -22
alsaucm: error failed to open sound card hw:1: Invalid argument
```

So I guess I need to get a recent snapshot or build from HEAD ?

**Comment by nodens** [comment]
Ok, confirmed it by looking at the code + comments on #154 :)
I'll try to build a local package and report.

**Comment by nodens** [comment]
Hi!

So, I tried building (and creating a package) for alsa-lib HEAD + alsa-utils just in case, but I guess something went wrong, since I get an error on alsaucm reload:

```$ alsaucm -c hw:M2 reload
alsaucm: conf.c:2291: snd_config_merge: Assertion `dst' failed.
Aborted
```
I'm guessing it's my build… any pointers? 

If there is a "build locally and test with LD_PRELOAD" method documented somewhere, That'd be great, since it's possible it's my "pseudo-update" of the Debian package which is causing the issue. I did what the maintainer would do for a new upstream release, but since I'm not familiar with alsa beside as a user, I imagine I did something wrong or forgot a step

Thanks!

**Comment by perexg** [comment]
I see the `reload` command issue - it's a bug in the recent code. I'll try to fix it later. Thanks for the report. It is not necessary to reload configuration, just test it `alsaucm -c hw:0 dump text` and with pulseaudio or pipewire (restart the sound daemon).

**Comment by nodens** [comment]
Ok, thanks.

Here's the dump:
```
$ alsaucm -c hw:M2 dump text
Verb.HiFi {
	Comment "Default Alsa Profile"
	Device.Line1 {
		Comment "Main Output L/R"
		Values {
			CaptureCTL "_ucm0001.hw:M2"
			PlaybackCTL "_ucm0001.hw:M2"
			PlaybackChannels 2
			PlaybackPCM "_ucm0001.minifuse2_stereo_out:M2,0,0,1"
			PlaybackPriority 300
		}
	}
	Device.Line2 {
		Comment "Loopback L/R"
		Values {
			CaptureCTL "_ucm0001.hw:M2"
			CaptureChannels 2
			CapturePCM "_ucm0001.minifuse2_stereo_in:M2,0,2,3"
			CapturePriority 200
			PlaybackCTL "_ucm0001.hw:M2"
			PlaybackChannels 2
			PlaybackPCM "_ucm0001.minifuse2_stereo_out:M2,0,2,3"
			PlaybackPriority 200
		}
	}
	Device.Line3 {
		Comment "Stereo Input 1+2 L/R"
		ConflictingDevices [
			Mic2,
			Mic1
		]
		Values {
			CaptureCTL "_ucm0001.hw:M2"
			CaptureChannels 2
			CapturePCM "_ucm0001.minifuse2_stereo_in:M2,0,0,1"
			CapturePriority 100
			PlaybackCTL "_ucm0001.hw:M2"
		}
	}
	Device.Mic1 {
		Comment "Mic/Line/Inst 1 (L)"
		ConflictingDevices [
			Line3
		]
		Values {
			CaptureCTL "_ucm0001.hw:M2"
			CaptureChannels 1
			CapturePCM "_ucm0001.minifuse2_mono_in:M2,0,0"
			CapturePriority 400
			PlaybackCTL "_ucm0001.hw:M2"
		}
	}
	Device.Mic2 {
		Comment "Mic/Line/Inst 2 (R)"
		ConflictingDevices [
			Line3
		]
		Values {
			CaptureCTL "_ucm0001.hw:M2"
			CaptureChannels 1
			CapturePCM "_ucm0001.minifuse2_mono_in:M2,0,1"
			CapturePriority 300
			PlaybackCTL "_ucm0001.hw:M2"
		}
	}
}
Verb.Direct {
	Comment "Direct MiniFuse 2"
	Device.Direct {
		Comment "Direct MiniFuse 2"
		Values {
			CaptureCTL "_ucm0001.hw:M2"
			CaptureChannels 4
			CapturePCM "_ucm0001.hw:M2"
			CapturePriority 1000
			PlaybackCTL "_ucm0001.hw:M2"
			PlaybackChannels 4
			PlaybackPCM "_ucm0001.hw:M2"
			PlaybackPriority 1000
		}
	}
}
```


The Direct _Verb worked as expected after I restarted pipewire. However, I cannot change the _Verb to HiFi using pavucontrol, I only see "Direct" and "Off" :thinking:

**Comment by perexg** [comment]
Could you run `spa-acp-tool -c 0 -vvvv list-ports` (replace zero with your ALSA card number) to check, if there's an error?

**Comment by nodens** [comment]
> Could you run `spa-acp-tool -c 0 -vvvv list-ports` (replace zero with your ALSA card number) to check, if there's an error?

There are:
```Set ucm verb to Direct
Trying _ucm0001.hw:M2 with SND_PCM_NO_AUTO_FORMAT ...
open '/dev/snd/pcmC1D0p' failed (-16)
Error opening PCM device _ucm0001.hw:M2: Device or resource busy
Set ucm verb to HiFi
Trying _ucm0001.minifuse2_stereo_out:M2,0,2,3 with SND_PCM_NO_AUTO_FORMAT ...
Unknown PCM minifuse2_stereo_out:M2,0,2,3
Error opening PCM device _ucm0001.minifuse2_stereo_out:M2,0,2,3: No such file or directory
Found 0 jacks.
activate profile: off (0)
```
(Full output: 
[minifuse2_spa-acp-tool_list-ports.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8770801/minifuse2_spa-acp-tool_list-ports.txt) )

> Also, please, provide output from `alsaucm -c 0 get _alibcfg`.

Here it is:
```
$ alsaucm -c hw:M2 get _alibcfg
  _alibcfg=ctl.hw {
	@args.0 CARD
	@args.CARD.type string
	type hw
	card $CARD
}
pcm.hw {
	@args {
		0 CARD
		1 DEV
		2 SUBDEV
		CARD.type string
		DEV.type integer
		SUBDEV.type integer
	}
	type hw
	card $CARD
	device $DEV
	subdevice $SUBDEV
}
pcm.minifuse2_mono_in {
	@args {
		0 CARD
		1 DEV
		2 CHN0
		CARD.type string
		DEV.type integer
		CHN0.type integer
	}
	ipc_key 6678293
	type dsnoop
	slave {
		pcm {
			type hw
			card $CARD
			device $DEV
			chmap [
				MONO
				MONO
				MONO
				MONO
			]
		}
		channels 4
	}
	bindings.0 $CHN0
}
```

**Comment by perexg** [comment]
Thanks. I updated my `macro` branch. Could you retest? Thank you.

**Comment by nodens** [comment]
Yay, it works now!
I can see and select both Direct and Default (so HiFi) profile in pavucontrol etc.

Great job, especially as this seems like it will be reusable for many "pro audio" interfaces using similar tricks. :)

I don't have the mean to check playing/recording via loopback right now, but I don't see why it wouldn't work - unless there is something wrong with my understanding of how the interface is supposed to work from documentation / other OS behaviours.

Thanks!

**Pull request closed without merging**
