### PR TITLE
Qcom volume fixes

### PR DESCRIPTION
**Pull request by jhovold**
Fix the Qualcomm sc8280xp and x1e80100 configurations which accidentally left the Speaker and Headphones mixer controls undefined so that the sound server falls back to software mixing. Also set the default volume levels in machine specific BootSequences so that the user can override the defaults.

### CODE REVIEW

**Review by Srinivas-Kandagatla — APPROVED** [review]
LGTM, should we have a Fixes by tag? Not sure how this works for this.

Reviewed-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>

**Review by Srinivas-Kandagatla — APPROVED** [review]
Reviewed-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>

**Review by Srinivas-Kandagatla — APPROVED** [review]
Reviewed-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>

**Comment by jhovold** [comment]
> LGTM, should we have a Fixes by tag? Not sure how this works for this.

It doesn't look like alsa-ucm-conf uses Fixes tags as we do in the kernel but rather to link to issues and pull requests in the github trackers.

> Reviewed-by: Srinivas Kandagatla [srinivas.kandagatla@linaro.org](mailto:srinivas.kandagatla@linaro.org)

Thanks for reviewing!

**Pull request closed without merging**
