### PR TITLE
ucm2: MediaTek: mt8395-evk: Add alsa-ucm support

### PR DESCRIPTION
**Pull request by zoran055**
Add alsa-ucm support for the MediaTek mt8395-evk platform.

### CODE REVIEW

**Comment by perexg** [comment]
Replace CR/LF at the end of line. Also, use tabulators for intention instead of spaces.

**Comment by zoran055** [comment]
Hi @perexg ,
I have already resolved the coding style problems and updated the new patch.
Two planned changes will be added in the coming days:
1. Set the default value for "PGA Volume".
2. Add the JackControl feature to HDMI and DP devices.

Many thanks.

**Comment by zoran055** [comment]
Hello @perexg ,
I have recently pushed a new commit. Could you please review it when you have some time?
Thank you in advance for your time, and I will eagerly await your feedback.

**Comment by zoran055** [comment]
Hello @perexg,
Could you please help to review #321 and #322?
I am grateful for your assistance.

**Comment by perexg** [comment]
Follow comments in PR #321 .

**Comment by zoran055** [comment]
> Follow comments in PR #321 .

Done

**Comment by zoran055** [comment]
Hi @perexg,
Could you please help to review #321 and #322?
Thank you very much!

**Pull request closed without merging**
