### PR TITLE
ucm2: Qualcomm sdm845 fixes HDMI select card and HiFi set DigitalVol

### PR DESCRIPTION
**Pull request by alimon**
Signed-off-by: Aníbal Limón <anibal.limon@linaro.org>

### CODE REVIEW

**Comment by perexg** [comment]
Merged in 3048ff7b15a922985499fa04b12b6abe929b8e4a  except the HDMI.conf change which is no-op (and my ucm validator does not like it). Thanks.

**Comment by perexg** [comment]
Wow. I was too quick. You cannot use PlaybackVolume twice. Only the last value is defined then ("RX2 Digital Volume"). Is sufficient to control only this volume for this device?

**Comment by alimon** [comment]
@perexg Right, fixed, thx.

**Comment by jkysela-rh** [comment]
Merged in eda02cf25751cc4792c5b160f42325c695342807 .

**Pull request closed without merging**
