### PR TITLE
acppdmmach: add support for ACP 7.0

### PR DESCRIPTION
**Pull request by superm1**
Starting with ACP 7.0 there is a generic 'acppdmmach' driver that will be utilized.

### CODE REVIEW

**Comment by superm1** [comment]
@pma1 can you please test this?

**Review by vijendarmukunda — COMMENTED** [review]
LGTM

**Comment by pma1** [comment]
@superm1 already done the change, but not working.

"Mic ACP LED" is not in list:
numid=12,iface=CARD,name='Headphone Jack'
numid=11,iface=CARD,name='Mic Jack'
numid=13,iface=CARD,name='Speaker Phantom Jack'
numid=10,iface=MIXER,name='Master Playback Switch'
numid=9,iface=MIXER,name='Master Playback Volume'
numid=2,iface=MIXER,name='Headphone Playback Switch'
numid=1,iface=MIXER,name='Headphone Playback Volume'
numid=16,iface=MIXER,name='PCM Playback Volume'
numid=8,iface=MIXER,name='Mic Boost Volume'
numid=7,iface=MIXER,name='Capture Switch'
numid=6,iface=MIXER,name='Capture Volume'
numid=5,iface=MIXER,name='Auto-Mute Mode'
numid=4,iface=MIXER,name='Speaker Playback Switch'
numid=3,iface=MIXER,name='Speaker Playback Volume'
numid=15,iface=PCM,name='Capture Channel Map'
numid=14,iface=PCM,name='Playback Channel Map'

**Comment by superm1** [comment]
> @superm1 already done the change, but not working.
> 
> "Mic ACP LED" is not in list: numid=12,iface=CARD,name='Headphone Jack' numid=11,iface=CARD,name='Mic Jack' numid=13,iface=CARD,name='Speaker Phantom Jack' numid=10,iface=MIXER,name='Master Playback Switch' numid=9,iface=MIXER,name='Master Playback Volume' numid=2,iface=MIXER,name='Headphone Playback Switch' numid=1,iface=MIXER,name='Headphone Playback Volume' numid=16,iface=MIXER,name='PCM Playback Volume' numid=8,iface=MIXER,name='Mic Boost Volume' numid=7,iface=MIXER,name='Capture Switch' numid=6,iface=MIXER,name='Capture Volume' numid=5,iface=MIXER,name='Auto-Mute Mode' numid=4,iface=MIXER,name='Speaker Playback Switch' numid=3,iface=MIXER,name='Speaker Playback Volume' numid=15,iface=PCM,name='Capture Channel Map' numid=14,iface=PCM,name='Playback Channel Map'

Thanks, it looks like the existing capture switch name won't work so some more changes will be needed.

```
card 2: acppdmmach [acp-pdm-mach], device 0: (null) dmic-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by superm1** [comment]
@vijendarmukunda would it make sense to add a stream name like older?
Something like this:

```c
diff --git a/sound/soc/amd/acp/acp70.c b/sound/soc/amd/acp/acp70.c
index 68d2590e1a4ef..6006d280747b4 100644
--- a/sound/soc/amd/acp/acp70.c
+++ b/sound/soc/amd/acp/acp70.c
@@ -126,6 +126,7 @@ static struct snd_soc_dai_driver acp70_dai[] = {
        .name = "acp-pdm-dmic",
        .id = DMIC_INSTANCE,
        .capture = {
+               .stream_name = "DMIC capture",
                .rates = SNDRV_PCM_RATE_8000_48000,
                .formats = SNDRV_PCM_FMTBIT_S32_LE,
                .channels_min = 2,
```

**Comment by vijendarmukunda** [comment]
> @vijendarmukunda would it make sense to add a stream name like older? Something like this:
> 
> ```c
> diff --git a/sound/soc/amd/acp/acp70.c b/sound/soc/amd/acp/acp70.c
> index 68d2590e1a4ef..6006d280747b4 100644
> --- a/sound/soc/amd/acp/acp70.c
> +++ b/sound/soc/amd/acp/acp70.c
> @@ -126,6 +126,7 @@ static struct snd_soc_dai_driver acp70_dai[] = {
>         .name = "acp-pdm-dmic",
>         .id = DMIC_INSTANCE,
>         .capture = {
> +               .stream_name = "DMIC capture",
>                 .rates = SNDRV_PCM_RATE_8000_48000,
>                 .formats = SNDRV_PCM_FMTBIT_S32_LE,
>                 .channels_min = 2,
> ```

@superm1 : No issues in adding the stream name.

**Comment by superm1** [comment]
> @superm1 : No issues in adding the stream name.

@pma1 :
https://lore.kernel.org/linux-sound/20241017174552.3194385-1-superm1@kernel.org/T/#u

**Comment by superm1** [comment]
@pma1 try again with what I force pushed.

**Comment by pma1** [comment]
@superm1  your new change still fail to work.

Here is the diff can work:

diff --git a/ucm2/HDA/HDA.conf b/ucm2/HDA/HDA.conf
index 83f3db2..d18bede 100644
--- a/ucm2/HDA/HDA.conf
+++ b/ucm2/HDA/HDA.conf
@@ -3,7 +3,7 @@ Syntax 6
 Define.Use ""  # a non-empty string to use UCM configuration for HDA devices
 Define.Done "" # a non-empty string to skip the end error
 
-Define.AcpCardId "$${find-card:field=name,return=id,regex='^acp(|6[23x])$'}"
+Define.AcpCardId "$${find-card:field=name,return=id,regex='^acp(|6[23x]|-pdm-mach)$'}"
 Define.DeviceMic "Mic"
 
 If.dualcodec {
diff --git a/ucm2/conf.d/acp-pdm-mach/acp-pdm-mach.conf b/ucm2/conf.d/acp-pdm-mach/acp-pdm-mach.conf
new file mode 120000
index 0000000..7298c24
--- /dev/null
+++ b/ucm2/conf.d/acp-pdm-mach/acp-pdm-mach.conf
@@ -0,0 +1 @@
+../../common/linked-card.conf
\ No newline at end of file

**Comment by superm1** [comment]
OK, did I get it right now?

**Comment by pma1** [comment]
@superm1 yes, it is OK now.
Thanks.

**Comment by superm1** [comment]
> @superm1 yes, it is OK now.
> Thanks.

Okay thanks. Kernel patches I linked will make it show up correctly in `arecord -l`

**Comment by pma1** [comment]
> > @superm1 yes, it is OK now.
> > Thanks.
> 
> Okay thanks. Kernel patches I linked will make it show up correctly in `arecord -l`

Is there any function change for kernel patches? I have to check if backport is needed.

**Comment by superm1** [comment]
> > > @superm1 yes, it is OK now.
> > > Thanks.
> > 
> > 
> > Okay thanks. Kernel patches I linked will make it show up correctly in `arecord -l`
> 
> Is there any function change for kernel patches? I have to check if backport is needed.

I don't know if there is anything functional UCM uses the stream name for, I just saw it as a gap from the `arecord -l`.  Is everything working with DMIC in the UI and the LED now as you expect?

**Comment by pma1** [comment]
> > > > @superm1 yes, it is OK now.
> > > > Thanks.
> > > 
> > > 
> > > Okay thanks. Kernel patches I linked will make it show up correctly in `arecord -l`
> > 
> > 
> > Is there any function change for kernel patches? I have to check if backport is needed.
> 
> I don't know if there is anything functional UCM uses the stream name for, I just saw it as a gap from the `arecord -l`. Is everything working with DMIC in the UI and the LED now as you expect?

Yes, with ucm change only, everything works fine.

**Pull request closed without merging**
