### PR TITLE
ucm2: add initial configuration for TRX40 Gigabyte Aorus Master Audio

### PR DESCRIPTION
**Pull request by perexg**
BugLink: https://github.com/alsa-project/alsa-ucm-conf/pull/25

### CODE REVIEW

**Comment by shrisha108** [comment]
Not sure what to do here. What files to put into /usr/share/alsa/ucm2/USB-Audio you were talking about?

**Comment by shrisha108** [comment]
link
this files?

**Comment by perexg** [comment]
Yes, https://github.com/alsa-project/alsa-ucm-conf/pull/72/files . Note that the first file is a symlink (not so much visible via this interface). You can download the raw files - click to the right file menu (...) click view and click [raw].

**Comment by shrisha108** [comment]
ok I put those three files into that folder and restart pulseaudio. So now I just have to try if optical SPDIF working?

**Comment by shrisha108** [comment]
So, I checked. from the gnome settings now I have hdmi audio controller, which is my graphics card and Digital output (S/PDIF) - USB Audio. Before I had two of them now just one. I choose it for output but still no sound.

**Comment by perexg** [comment]
> So, I checked. from the gnome settings now I have hdmi audio controller, which is my graphics card and Digital output (S/PDIF) - USB Audio. Before I had two of them now just one. I choose it for output but still no sound.

As I wrote in #25 , show the verbose PA output...

**Comment by shrisha108** [comment]
thats more then 3000 lines :)
[output.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5814132/output.txt)

**Comment by perexg** [comment]
Please, create correct link `Gigabyte-Aorus-Master-Front-Audio.conf -> ../module/lib/linked.conf` in the USB-Audio directory and update Gigabyte-Aorus-Master-Main-Audio-HiFi.conf file from github again.

**Comment by shrisha108** [comment]
Ok I updated Gigabyte-Aorus-Master-Main-Audio-HiFi.conf But Gigabyte-Aorus-Master-Front-Audio.conf seems fine
text

**Comment by shrisha108** [comment]
sorry, is this correct way to do it?
sudo ln -s /usr/share/alsa/ucm2/USB-Audio/Gigabyte-Aorus-Master-Front-Audio.conf /usr/share/alsa/ucm2/module/lib/linked.conf

**Comment by perexg** [comment]
Symlink:

```
# ln -s /usr/share/alsa/ucm2/module/lib/linked.conf /usr/share/alsa/ucm2/USB-Audio/Gigabyte-Aorus-Master-Front-Audio.conf
# ls -l /usr/share/alsa/ucm2/USB-Audio/Gigabyte-Aorus-Master-Front-Audio.conf
   /usr/share/alsa/ucm2/USB-Audio/Gigabyte-Aorus-Master-Front-Audio.conf -> /usr/share/alsa/ucm2/module/lib/linked.conf
# cat /usr/share/alsa/ucm2/USB-Audio/Gigabyte-Aorus-Master-Front-Audio.conf
Syntax 3

ValueDefaults {
	Linked 1
}
```

I updated the Gigabyte-Aorus-Master-Main-Audio-HiFi.conf on github again.

**Comment by shrisha108** [comment]
Ok, again updated Gigabyte-Aorus-Master-Main-Audio-HiFi.conf  and new output here:
[output3.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5814764/output3.txt)

**Comment by perexg** [comment]
Mea culpa. The symlink should be:

```ln -s /usr/share/alsa/ucm2/module/lib/linked.conf /usr/share/alsa/ucm2/USB-Audio/Gigabyte-Aorus-Master-Front-Headphone.conf```

**Comment by shrisha108** [comment]
Your fault? Wait a minute! I'm from Moldova, how did you know that will understand? :) New output:
[output4.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5815209/output4.txt)

**Comment by shrisha108** [comment]
Should I delete Gigabyte-Aorus-Master-Front-Audio.conf symlink?

**Comment by perexg** [comment]
> Should I delete Gigabyte-Aorus-Master-Front-Audio.conf symlink?

Yes, but it's harmless.

**Comment by perexg** [comment]
> New output:  [output4.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5815209/output4.txt)

PA is now configured. But there's an issue which apparently requires manual selection of the output device. Use pavucontrol to select the device (last tab - settings).

**Comment by shrisha108** [comment]
Ok, that what I have there:
image

**Comment by perexg** [comment]
Could you comment out `JackControl "Line Out Jack"` line in Gigabyte-Aorus-Master-Main-Audio-HiFi.conf (add # before text).

**Comment by shrisha108** [comment]
image
like this?

**Comment by perexg** [comment]
> like this?

Yes.

**Comment by shrisha108** [comment]
with commented or commented that line still USB audio - Default Alsa profile (unavailable)
When I commented JackControl "Line Out Jack"  I got system freezes avery few minutes. So still no sound :(

**Comment by shrisha108** [comment]
Sorry that it taking so long. I have to fully restart computer systemctl --user start pulseaudio.service and socket command is not enough to check if sound is working

**Comment by perexg** [comment]
I need the PA logs again.

**Comment by shrisha108** [comment]
[output5.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5815546/output5.txt)
here you go

**Comment by perexg** [comment]
Try comment all JackControl lines. It seems like a PA fault somewhere.

**Comment by shrisha108** [comment]
what about JackCTL "hw:${var:SecondaryCardId}" ?

**Comment by shrisha108** [comment]
Ok now pavucontrol in configuration tab "USB audio - Default Alsa profile"  is available. (unavailable) disapeared.
But still no sound when S/PDIF Out - USB Audio is selected :( 
new output:
[output6.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5815801/output6.txt)

**Comment by shrisha108** [comment]
I can give you anydesk access if it will make everything much easier for you. I'm not privacy freak.

**Comment by perexg** [comment]
You should see four sinks. You may try also 'Line Out' (devices may be switched). If it does not work either, it's probably a driver issue. It's best to try with the ALSA utilities to check the functionality: `speaker-test -D hw:Audio,0`, `speaker-test -D hw:Audio,1`, `speaker-test -D hw:Audio,3` when PA is not active. Also, you may play with the mixer `alsamixer -D hw:Audio` directly. If you figure, how S/PDIF device works, we can update the UCM configuration.

**Comment by shrisha108** [comment]
I tried ALSA utilities to check the functionality. pulseaudio.service and socket are stopped. 

```
[shrisha@fedora-home ~]$ speaker-test -D hw:Audio,0

speaker-test 1.2.4

Playback device is hw:Audio,0
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
Channels count (1) not available for playbacks: Invalid argument
Setting of hwparams failed: Invalid argument
[shrisha@fedora-home ~]$ speaker-test -D hw:Audio,1

speaker-test 1.2.4

Playback device is hw:Audio,1
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
Channels count (1) not available for playbacks: Invalid argument
Setting of hwparams failed: Invalid argument
[shrisha@fedora-home ~]$ speaker-test -D hw:Audio,3

speaker-test 1.2.4

Playback device is hw:Audio,3
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
Channels count (1) not available for playbacks: Invalid argument
Setting of hwparams failed: Invalid argument
```

**Comment by shrisha108** [comment]
SUCCESS!!! I found it! aplay --device=hw:2,1 sound.wav

**Comment by shrisha108** [comment]
What should I do next. Is there anything else you need from me?

**Comment by perexg** [comment]
I updated the .conf file, but you may need to comment out the JackControl lines if things does not work again. I shuffled the priority settings, so it may make a difference for the jack handling in PA.

**Comment by shrisha108** [comment]
Alright. I updated Gigabyte-Aorus-Master-Main-Audio-HiFi.conf file. Started pulseaudio and it's working now! FINALLY!!! Even it's still shows (unavailable) in pavucontrol in configuration tab. After I commented all Jack Control lines (unavailable) disappeared and it's still works. Thank you so much!!! I'm very appreciate your help!

**Comment by shrisha108** [comment]
After listening music for a 10 minutes I noticed very occasional clipping and stuttering. Is there is anything can be adjusted?

**Comment by shrisha108** [comment]
Correction: After commenting all JackControl lines and full restart sound disappear again. So I uncomment them and full restart and it's work again.

**Comment by MarijnS95** [comment]
@perexg For my understanding of UCM2 - this file is pretty similar to `Realtek-ALC1220-VB-Desktop-HiFi.conf` with minor modifications - but UCM2 doesn't allow overwriting or composing the identical sections (like input devices) together?

**Comment by perexg** [comment]
We can do a split to separate files and include the common parts, but I think that it's not worth for this simple configs at the moment.

**Comment by shrisha108** [comment]
News! Today morning Fedora 33 pushed new updates and after restart S/PDIF stopped working again. What I remember pipewire packages was updated. Anyway. USB audio device 3,0 3,1 and 3,3 now. I don't if this related to update but there is no sound again. 
New output log:

[output7.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5823924/output7.txt)

**Comment by perexg** [comment]
I don't see any problematic behaviour in your log (except the profile availability). You may try to play with the jack detection configuration like before. I filled pulseaudio for this issue here: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1103 .

**Comment by shrisha108** [comment]
Somehow after few reboots it's fixed itselfs. Don't know what was that. Now it is working. With occasional clipping and stuttering but working.

**Comment by shrisha108** [comment]
Today it's happen again. And I found the problem. The device S/PDIF cable connected to should be on. Otherwise it will not work again. So I turn-on device first and start computer and everything is fine then. Not ideal solution though.

**Comment by perexg** [comment]
It seems like a driver issue. Report it to the appropriate bug tracker: https://bugzilla.kernel.org

**Comment by shrisha108** [comment]
I updated my originally reported bug.

**Pull request merged**
