### PR TITLE
ucm2: sof-soundwire: add basic settings for RT1318 SDCA device

### PR DESCRIPTION
**Pull request by shumingfan**
Add support for rt1318 amplifier

Signed-off-by: Shuming Fan <shumingf@realtek.com>

### CODE REVIEW

**Comment by perexg** [comment]
It seems fine, but I would like to know, if all of those amplifier chips are really missing the analog volume control in the hardware. If there's analog volume control, it should be exposed in the kernel driver to the user space and described in the UCM configuration.

**Comment by plbossart** [comment]
> It seems fine, but I would like to know, if all of those amplifier chips are really missing the analog volume control in the hardware. If there's analog volume control, it should be exposed in the kernel driver to the user space and described in the UCM configuration.

Even if they did, we have a plumbing issue @perexg. In the case where there are two amplifiers, we would need to have two volumes applied at the same time in two different hardware devices. This is not possible with older SoundWire devices, but with newer SDCA-based devices there are means to synchronize volume changes across related devices. It'll require a lot more work to implement this I am afraid, for now only the PCM is synchronized.

**Comment by perexg** [comment]
I just feel that we miss something which was a "hard" standard before (analog volume control). It may affect also the power consumption of the amplifier. Having more components is just an implementation detail. We can do a remap for those devices in the user space, but the drivers should expose this functionality (if hw is capable, of course).

**Comment by plbossart** [comment]
oh I completely agree with you @perexg that this is something we need to work on. 

But as you said we need to create a 'virtual' control that relays the user choices to separate devices and when possible we have to synchronize the control .put sequences. Our Windows friends are having the same issue btw, when the 'amplifier function' is implemented with different devices new plumbing is required across the stack.

**Pull request closed without merging**
