### PR TITLE
Add UCM2 configuration for Behringer UMC404HD

### PR DESCRIPTION
**Pull request by Janhouse**
The only difference between UMC204HD and UMC404HD are the 2 additional inputs and a different USB device ID. Tested with my 404HD, works great.

### CODE REVIEW

**Comment by Janhouse** [comment]
@perexg does this look OK?

**Comment by tam1m** [comment]
I was about send the same PR when I found yours. This works perfectly fine. The one thing I noticed in your code is capture priorities for MIC 1 to 4. MIC1 CapturePriority set to 200 and all the others at 100. Guess, this was just oversight from copying the UMC204HD config?

**Comment by Janhouse** [comment]
@tam1m thanks for the comment. I am actually not sure what the priority should be. I presume higher number means higher priority. Can't the rest of the inputs stay at 100? :slightly_smiling_face:

**Comment by perexg** [comment]
Thanks. The priorities should be different, but they don't play any role for devices without jack detection mechanism. I've changed them anyway.

**Pull request closed without merging**
